import { Inter } from "next/font/google";
import "../styles/globals.scss";
import { ToastContainer } from "react-toastify";

import {
  Allura,
  Roboto_Mono,
  Londrina_Outline,
  Lemonada,
  Montserrat_Alternates,
  Libre_Franklin,
} from "next/font/google";
import Script from "next/script";
const allura = Allura({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-allura",
});
const montserrat_Alternates = Montserrat_Alternates({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-Montserrat_Alternates",
});
const libre_Franklin = Libre_Franklin({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-Libre_Franklin",
});
const lemonada = Lemonada({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-lemonada",
});
const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-roboto-mono",
});
const londrinaoutline = Londrina_Outline({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-londrina-outline",
});

export const metadata = {
  title: "SHA&RI",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/logoSHARI.jpg" }],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />

        <title>Kuri Organics - Best Organic Essential Oils</title>

        <meta
          name="description"
          content="Find the best products across various categories, handpicked just for you. Explore top-rated items, customer favorites, and exclusive deals all in one place."
        />

        <meta
          name="keywords"
          content="best products, top-rated, shopping, exclusive deals, electronics, fashion, beauty, home essentials"
        />

        <meta name="author" content="Your Name or Your Brand" />

        <link rel="canonical" href="https://www.yourwebsite.com" />

        <meta
          property="og:title"
          content="Your Website Name - Best Products for Your Needs"
        />
        <meta
          property="og:description"
          content="Explore top-rated products across various categories and get exclusive deals."
        />
        <meta property="og:url" content="https://www.yourwebsite.com" />
        <meta property="og:type" content="website" />
        <meta
          property="og:image"
          content="https://www.yourwebsite.com/images/og-image.jpg"
        />

        <meta name="twitter:card" content="summary_large_image" />
        <meta
          name="twitter:title"
          content="Your Website Name - Best Products for Your Needs"
        />
        <meta
          name="twitter:description"
          content="Discover the best products and exclusive deals tailored to your preferences."
        />
        <meta
          name="twitter:image"
          content="https://www.yourwebsite.com/images/twitter-image.jpg"
        />

        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
      </head>

      <meta name="description" content="Generated by create next app" />

      <body
        className={`${allura.variable} ${montserrat_Alternates.variable} ${robotoMono.variable} ${londrinaoutline.variable}  ${lemonada.variable}`}
      >
        <ToastContainer />

        {children}
      </body>
    </html>
  );
}
